// Question.java - Adding missing getTopic() method
package com.learningassistant.models;

import lombok.Data;
import lombok.NoArgsConstructor;
import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Data
@NoArgsConstructor
@Entity
@Table(name = "questions")
public class Question {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Lob
    @Column(nullable = false)
    private String text;

    @Column(name = "question_type")
    @Enumerated(EnumType.STRING)
    private QuestionType type;

    @Column(name = "difficulty_level")
    private Integer difficultyLevel; // 1-10

    @ManyToOne
    @JoinColumn(name = "quiz_id")
    private Quiz quiz;

    // Add topic relationship to fix error in Image 2
    @ManyToOne
    @JoinColumn(name = "topic_id")
    private Topic topic;

    @OneToMany(mappedBy = "question", cascade = CascadeType.ALL)
    private List<Answer> answers = new ArrayList<>();

    public enum QuestionType {
        MULTIPLE_CHOICE, TRUE_FALSE, FILL_IN_BLANK, SHORT_ANSWER
    }

    // This getter is automatically generated by Lombok's @Data annotation,
    // but adding it explicitly for clarity
    public Topic getTopic() {
        return this.topic;
    }

    public void setTopic(Topic topic) {
        this.topic = topic;
    }
}
